// <auto-generated />
namespace Rock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ESignature_SignatureVerificationHash : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ESignature_SignatureVerificationHash));
        
        string IMigrationMetadata.Id
        {
            get { return "202201142157122_ESignature_SignatureVerificationHash"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
